apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-charts.fullname" . }}
  labels:
    {{- include "my-charts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-charts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository | quote}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}